"""[T1] Lifetimes of Gaussians in the time-indexed map (Khronos eq. 5: the measurement of time t is generated by the
scene of time t), pure tensor logic of backends/game/game.py.

A Gaussian stands for a piece of the scene, so its lifetime is that piece's, not the moment GaME happened to create
it: a background Gaussian exists from -infinity (a static wall exists at every keyframe, also those before the
Gaussian was seeded) until the layer's evidence ends it (retire: death_evidence); an object Gaussian lives from the
birth of the object state it belongs to until that state ends (the layer's state intervals = the registry's
intervals: death_state). Its state is the latest state of its identity born at or before its creation. A Gaussian of
no known state (an identity the layer has no interval for yet, or one created before its identity's first state, or
not yet labelled) keeps its creation stamp as birth.
"""
from __future__ import annotations

from typing import Dict, List, Optional, Tuple

import torch

INT64_MAX = torch.iinfo(torch.int64).max
INT64_MIN = torch.iinfo(torch.int64).min


def birth(identity: torch.Tensor, created: torch.Tensor, state_birth: torch.Tensor, bg_birth=None) -> torch.Tensor:
    """Per Gaussian its birth: background (identity 0) -infinity, the birth of its state when known, else created.
    [S1] bg_birth (an int or a tensor per Gaussian): the background's birth is the first stamp of the session whose
    data built the Gaussian (the split: a session's present describes the scene from its first frame on, the history
    before it is the memory) instead of -infinity."""
    b = torch.where(state_birth < INT64_MAX, state_birth, created)
    floor = torch.full_like(created, INT64_MIN) if bg_birth is None else (
        bg_birth if torch.is_tensor(bg_birth) else torch.full_like(created, int(bg_birth)))
    return torch.where(identity == 0, floor, b)


def end(death_state: torch.Tensor, death_evidence: torch.Tensor, death_prune=None) -> torch.Tensor:
    """Per Gaussian its end: the earliest of its state's end, the layer's evidence end and [P1] the end GaME's own
    opacity prune gave it (a Gaussian of an earlier session the optimiser no longer supports is ended, not deleted,
    so the maps of its keyframes' times keep it)."""
    e = torch.minimum(death_state, death_evidence)
    return e if death_prune is None else torch.minimum(e, death_prune)


def alive_at(t: int, identity: torch.Tensor, created: torch.Tensor, state_birth: torch.Tensor,
             death_state: torch.Tensor, death_evidence: torch.Tensor, bg_birth=None, death_prune=None) -> torch.Tensor:
    return (birth(identity, created, state_birth, bg_birth) <= t) & (t < end(death_state, death_evidence, death_prune))


def state_membership(identity: torch.Tensor, created: torch.Tensor,
                     intervals: Dict[int, List[Tuple[int, Optional[int]]]],
                     session_start: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
    """(state_birth, death_state) of every Gaussian under the state intervals {identity: [(birth, death or None)]}:
    the state of a Gaussian is the latest state of its identity born at or before its creation; it lives from that
    state's birth until the state ends. A label with no interval at all -> (INT64_MAX, INT64_MAX): no state birth
    known, no state end (the pending window of a state the registry has not born yet).

    [O2] A Gaussian of label l created before l's first state (its earliest birth) is not that state's geometry: the
    fork builds a state only from the frames of its reconstruction (session_refusion.cpp:138-148, 789-792 cut an
    object's pixels before t_L, the first frame of its CURRENT state) and shows no object face whose node is not
    current (:1071-1081, R15). Such a Gaussian lives from its creation and ends when the first state of its label is
    born: what it showed before (a leaked label on a wall, the object before it settled) stays in the maps of that
    time; from the state's birth on only the state's own Gaussians are the object. (session_start is accepted for
    the backend's call and unused: the rule needs no session.)"""
    sb = torch.full_like(created, INT64_MAX)
    ds = torch.full_like(created, INT64_MAX)
    for ident, lst in intervals.items():
        rows = torch.nonzero(identity == ident).squeeze(1)
        if not len(rows) or not lst:
            continue
        births = torch.tensor([b for b, _ in lst], dtype=torch.int64, device=created.device)
        deaths = torch.tensor([INT64_MAX if d is None else d for _, d in lst], dtype=torch.int64, device=created.device)
        order = torch.argsort(births)
        births, deaths = births[order], deaths[order]
        pos = torch.searchsorted(births, created[rows], right=True) - 1
        ok = pos >= 0
        sb[rows[ok]] = births[pos[ok]]
        ds[rows[ok]] = deaths[pos[ok]]
        early = rows[~ok]                                                                     # [O2]
        sb[early] = created[early]
        ds[early] = births[0]
    return sb, ds
